version: 2
jobs:
 cypress_test:
    docker:
      - image: cypress/base:10
    parallelism: 4
    steps:
      - checkout
      - run: npm install cypress --save-dev
      - run:
         name: Run cypress e2e tests
         command: ./node_modules/.bin/cypress run --spec `circleci tests glob "**/examples/*.spec.js" | circleci tests split| tr '\n' ','`


workflows:
   version: 2
   e2e_tests:
     jobs:
       - cypress_test

    