version: 2
jobs:
 cypress_test:
    docker:
      - image: cypress/base:10
    parallelism: 4
    steps:
      - checkout
      - run:
          name: install dependancies
          command: |
            npm ci
            mkdir /tmp/test-results
      - run:
         name: Run cypress e2e tests
         command: $(npm bin)/cypress run --spec `circleci tests glob "**/examples/*.spec.js" | circleci tests split| tr '\n' ','`
      - store_test_results:
          path: /tmp/test-results


workflows:
   version: 2
   e2e_tests:
     jobs:
       - cypress_test

    